import {qualityProfile,createMotion,landingImpulse,advanceMotion} from './presentation.js';
import {leaderboard,saveScore} from './leaderboard.js';
import {Engine,Scene,Vector3,Color3,Color4,FreeCamera,HemisphericLight,DirectionalLight,PointLight,SpotLight,Quaternion,SSAO2RenderingPipeline,ShadowGenerator,TransformNode,SceneLoader,PBRMaterial,Texture,HDRCubeTexture,DefaultRenderingPipeline} from '@babylonjs/core';
import '@babylonjs/loaders/glTF/index.js';
import {createState,step,row,score,LANE,ROAD_CENTER,ROAD_WIDTH,STEP,random,ROW_SPACING} from './simulation.js';
const $=id=>document.getElementById(id), show=(id,on=true)=>$(id).classList.toggle('hidden',!on);
const canvas=$('game');const engine=new Engine(canvas,true,{stencil:true,preserveDrawingBuffer:true});
let quality;
updateResolution();
// Babylon divides CSS dimensions by this value; high-DPI needs its reciprocal.
function updateResolution(){quality=qualityProfile({coarse:matchMedia('(pointer:coarse)').matches,width:innerWidth,dpr:devicePixelRatio,webgl2:engine.webGLVersion>1});engine.setHardwareScalingLevel(1/quality.pixelRatio);engine.resize();canvas.dataset.renderScale=String(quality.pixelRatio);canvas.dataset.quality=quality.name;}

const scene=new Scene(engine);scene.clearColor=new Color4(.69,.82,.79,1);scene.fogMode=Scene.FOGMODE_LINEAR;scene.fogStart=95;scene.fogEnd=230;scene.fogColor=new Color3(.69,.82,.79);
const camera=new FreeCamera('follow',new Vector3(10,7,-12),scene);camera.minZ=.1;camera.maxZ=230;camera.fov=.8;
const hemi=new HemisphericLight('sky',new Vector3(0,1,0),scene);hemi.intensity=.45;hemi.groundColor=new Color3(.12,.17,.19);
const sun=new DirectionalLight('sun',new Vector3(-.65,-1,.65),scene);sun.position=new Vector3(30,50,-25);sun.intensity=2.2;sun.autoUpdateExtends=false;sun.orthoLeft=-24;sun.orthoRight=24;sun.orthoTop=28;sun.orthoBottom=-20;sun.shadowMinZ=1;sun.shadowMaxZ=120;
const shadows=new ShadowGenerator(quality.shadowSize,sun);shadows.usePercentageCloserFiltering=true;shadows.filteringQuality=ShadowGenerator.QUALITY_MEDIUM;shadows.bias=.0002;shadows.normalBias=.008;shadows.setDarkness(.35);
const headlight=new SpotLight('rider-headlight',new Vector3(0,1,1),new Vector3(0,-.1,1),Math.PI/3,2,scene);headlight.diffuse=new Color3(1,.9,.72);headlight.range=40;headlight.intensity=0;
const tunnelLights=Array.from({length:3},(_,i)=>{const l=new PointLight('tunnel-pool-'+i,new Vector3(0,6,0),scene);l.diffuse=i%2?new Color3(.54,.78,1):new Color3(1,.78,.51);l.range=23;l.intensity=0;return l;});

scene.imageProcessingConfiguration.toneMappingEnabled=true;scene.imageProcessingConfiguration.exposure=1.0;scene.imageProcessingConfiguration.contrast=1.12;
const env=new HDRCubeTexture('./assets/textures/sky.hdr',scene,128,false,true,false,true);scene.environmentTexture=env;scene.environmentIntensity=.7;const skybox=scene.createDefaultSkybox(env,true,1000,.12);skybox.isPickable=false;skybox.applyFog=false;
const pipeline=new DefaultRenderingPipeline('finish',true,scene,[camera]);pipeline.samples=quality.samples;pipeline.fxaaEnabled=engine.webGLVersion<2;pipeline.bloomEnabled=quality.bloom;pipeline.bloomThreshold=1.2;pipeline.bloomWeight=.09;pipeline.bloomKernel=32;
let ambientOcclusion=null;
if(quality.ssao){ambientOcclusion=new SSAO2RenderingPipeline('contact-occlusion',scene,{ssaoRatio:.5,blurRatio:1},[camera]);ambientOcclusion.radius=.28;ambientOcclusion.totalStrength=.25;ambientOcclusion.samples=8;ambientOcclusion.expensiveBlur=false;}
const asphalt=new PBRMaterial('rough asphalt',scene);asphalt.albedoTexture=new Texture('./assets/textures/asphalt.jpg',scene);asphalt.bumpTexture=new Texture('./assets/textures/asphalt-normal.jpg',scene);asphalt.bumpTexture.level=.32;asphalt.albedoColor=new Color3(.63,.68,.73);asphalt.roughness=.88;asphalt.metallic=0;asphalt.maxSimultaneousLights=6;for(const t of [asphalt.albedoTexture,asphalt.bumpTexture]){t.uScale=5;t.vScale=7;t.anisotropicFilteringLevel=quality.anisotropy;}
asphalt.metallicTexture=new Texture('./assets/textures/asphalt-roughness.jpg',scene);asphalt.metallicTexture.gammaSpace=false;asphalt.metallicTexture.uScale=5;asphalt.metallicTexture.vScale=7;asphalt.metallicTexture.anisotropicFilteringLevel=quality.anisotropy;asphalt.useRoughnessFromMetallicTextureAlpha=false;asphalt.useRoughnessFromMetallicTextureGreen=true;asphalt.useMetallnessFromMetallicTextureBlue=false;
const gold=new PBRMaterial('polished gold',scene);gold.albedoColor=new Color3(1,.64,.07);gold.metallic=.82;gold.roughness=.12;gold.emissiveColor=new Color3(.12,.065,0);
const goldHighlight=new PBRMaterial('gold rim',scene);goldHighlight.albedoColor=new Color3(1,.86,.35);goldHighlight.metallic=.72;goldHighlight.roughness=.16;goldHighlight.emissiveColor=new Color3(.16,.08,.005);
const whiteLine=new PBRMaterial('worn road paint',scene);whiteLine.albedoColor=new Color3(.91,.9,.81);whiteLine.metallic=0;whiteLine.roughness=.9;whiteLine.emissiveColor=new Color3(.018,.018,.015);
const yellow=new PBRMaterial('road centerline',scene);yellow.albedoColor=new Color3(1,.63,.08);yellow.roughness=.8;

const glowMaterials=[];
const assets=new Map(), world=[], visibleObjects=new Map(),oncoming=[];let rider,racer,helmet,bike,wheels=[],handlebar,spineJoint,headJoint,spineRest;const motion=createMotion();
let mode='home',state=createState(2026),run=null,pending=[],acc=0,visualTime=22,lastTime=performance.now(),lastBiome=-1,saved=false;
const review=location.hostname==='localhost'?new URLSearchParams(location.search):new URLSearchParams();if(review.has('scene'))state.distance=({city:36,forest:396,tunnel:756,coast:1116})[review.get('scene')]||0;if(review.get('light')==='night')visualTime=84;
let renderDt=0,crashAge=0;
let soundOn=localStorage.getItem('rush-sound')!=='off',audio,engineOsc,engineGain,windGain,crashBuffer;
$('sound').textContent='音效 '+(soundOn?'開':'關');$('sound').setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');
const files=['cloudline-tower','meadow-apartments','sageworks-offices','cornerleaf-cafe','freshfield-market','cloud-oak','alpine-pine','sakura-bloom','autumn-maple','classic-street-lamp','gold-coin','park-bench','road-sportbike','racing-rider','helmet','ramp','sea','beach','coastal-palm','asphalt','lane-mark','tile-low','construction-barrier','sedan','taxi','delivery','suv','cone','box','overheadRound','grass','rail'];
function meshes(node){return node.getChildMeshes(false);}
function prefab(name,width=null){const c=assets.get(name);const instance=c.instantiateModelsToScene(n=>n+'-copy',false,{doNotInstantiate:['asphalt','lane-mark','gold-coin','road-sportbike'].includes(name)});const root=new TransformNode(name,scene);instance.rootNodes.forEach(n=>n.parent=root);root.computeWorldMatrix(true);const b=root.getHierarchyBoundingVectors(true);const size=b.max.subtract(b.min);const s=width===null?1:width/size.x;root.scaling.setAll(s);const offset=new Vector3(-(b.min.x+b.max.x)/2,-b.min.y,-(b.min.z+b.max.z)/2);instance.rootNodes.forEach(n=>n.position.addInPlace(offset));root.metadata={original:size,instance};meshes(root).forEach(m=>{if(m.sourceMesh)m.sourceMesh.receiveShadows=true;else m.receiveShadows=true;m.isPickable=false;});return root;}
function heightModel(name,h){const n=prefab(name);n.scaling.setAll(h/n.metadata.original.y);return n;}
function sizeModel(name,w,h,d){const n=prefab(name);const s=n.metadata.original;n.scaling.set(w/s.x,h/(s.y||1),d/s.z);return n;}
const curve=d=>Math.sin(d/170)*10+Math.sin(d/420)*18;
const hill=d=>Math.sin(d/110)*2.5+Math.sin(d/250)*5;
const slope=d=>(hill(d+1)-hill(d-1))/2;
const turn=d=>(curve(d+1)-curve(d-1))/2;
function addWorld(n,d,x=0,y=0){n.position.set(x,y,d);world.push({n,d});return n;}
const BIOMES=['城市','森林公路','星光隧道','海岸公路'];
function biomeAt(d){return Math.floor(Math.max(0,d)/360)%4;}
function buildSegment(index){const d=index*18,biome=biomeAt(d);const root=new TransformNode('segment-'+index,scene);root.position.z=d;const put=(n,x,y,z)=>{n.parent=root;n.position.set(x,y,z);return n;};
 const road=sizeModel('asphalt',ROAD_WIDTH,.02,18.5);meshes(road).forEach(m=>m.material=asphalt);put(road,ROAD_CENTER,-.025,0);
 for(const x of [ROAD_CENTER-LANE,ROAD_CENTER+LANE])for(const z of [-6,3]){const mark=sizeModel('lane-mark',.12,.01,3.2);meshes(mark).forEach(m=>m.material=whiteLine);put(mark,x,.035,z);}
 for(const x of [ROAD_CENTER-.13,ROAD_CENTER+.13]){const mark=sizeModel('lane-mark',.12,.01,18.5);meshes(mark).forEach(m=>m.material=yellow);put(mark,x,.007,0);}
 for(const x of [ROAD_CENTER-LANE*2-.1,ROAD_CENTER+LANE*2+.1]){const mark=sizeModel('lane-mark',.16,.01,18.5);meshes(mark).forEach(m=>m.material=whiteLine);put(mark,x,.035,0);}
 for(const side of [-1,1]){
  if(biome!==3)put(sizeModel('grass',42,.15,18.4),side*25.6+ROAD_CENTER,-.22,0);
  if(biome===0){put(sizeModel('tile-low',2.2,.2,18.02),side*7.7+ROAD_CENTER,-.12,0);const building=prefab(['cornerleaf-cafe','meadow-apartments','freshfield-market','sageworks-offices','cloudline-tower'][Math.abs(index*3+(side>0?1:0))%5],7.3); put(building,side*13.4+ROAD_CENTER,0,0);building.rotation.y=side>0?-Math.PI/2:Math.PI/2;const tree=prefab('sakura-bloom',3.2);put(tree,side*8.1+ROAD_CENTER,.05,6);if(index%2===0)put(prefab('park-bench',2),side*7.7+ROAD_CENTER,.1,-5);}
  if(biome===1){for(let k=0;k<3;k++){const t=prefab(['cloud-oak','alpine-pine','autumn-maple'][(k+Math.abs(index))%3],3.5+random(index+50,k+side+2)*2);put(t,side*(10.4+k*5)+ROAD_CENTER,0,-7+k*5);}put(sizeModel('rail',.25,.65,18),side*7.2+ROAD_CENTER,.1,0);}
  if(biome===0||biome===1){const lamp=heightModel('classic-street-lamp',5.4);put(lamp,side*7.7+ROAD_CENTER,0,-6);lamp.rotation.y=side>0?Math.PI:0;}
 }
 if(biome===3){put(sizeModel('sea',100,.5,19),-62.8,-1.25,0);put(sizeModel('beach',16,.55,19),-16.8,-.8,0);put(sizeModel('beach',40,.55,19),25,-.7,0);put(prefab('coastal-palm',5.5),7,.05,0);put(prefab('coastal-palm',4.5),13,.05,7);put(sizeModel('rail',.25,.75,18.5),-8.5,0,0);if(index%3===0)put(prefab('cornerleaf-cafe',7.5),18,0,-4);}
 if(biome===2){put(sizeModel('overheadRound',42,21,18.7),ROAD_CENTER,-.15,0);for(const side of [-1,1]){const light=heightModel('classic-street-lamp',5.3);put(light,side*7.6+ROAD_CENTER,.1,0);}}
 meshes(root).forEach(m=>{if(!/road|grass|asphalt|lane|mark/i.test(m.name))shadows.addShadowCaster(m);if(m.material)m.material.unlit=false;});world.push({n:root,d,segment:index});return root;
}
let lastSegment=-3;
function updateWorld(distance){const target=Math.floor((distance+220)/18);while(lastSegment<target){lastSegment++;buildSegment(lastSegment);}for(let i=world.length-1;i>=0;i--){const o=world[i];o.n.position.set(curve(o.d)-curve(distance),hill(o.d)-hill(distance),o.d-distance);o.n.rotation.y=(o.type==='ramp'?Math.PI:0)+Math.atan(turn(o.d));o.n.rotation.x=-Math.atan(slope(o.d));if(o.n.position.z< -36){o.n.dispose();world.splice(i,1);}}
 const near=Math.max(0,Math.floor((distance-150)/ROW_SPACING));const wanted=new Set();
 for(let i=near;i<near+7;i++)for(const o of row(state.seed,i)){
  if(o.d-distance< -8||o.d-distance>220||state.consumed.has(o.id))continue;wanted.add(o.id);let n=visibleObjects.get(o.id);
  if(!n){n=prefab(o.type==='coin'?'gold-coin':o.type==='barrier'?'construction-barrier':o.type,o.type==='coin'?.85:o.type==='barrier'||o.type==='ramp'?2.5:o.type==='cone'?.85:o.type==='box'?1.5:2.1);if(o.type==='barrier'){const sz=n.metadata.original;n.scaling.set(2.5/sz.x,1.1/sz.y,.55/sz.z);}if(o.type==='ramp'){const sz=n.metadata.original;n.scaling.set(2.5/sz.x,1/sz.y,4.5/sz.z);n.rotation.y=Math.PI;}if(o.type==='coin')meshes(n).forEach(m=>m.material=m.name.includes('highlight')?goldHighlight:gold);visibleObjects.set(o.id,n);if(o.type!=='coin')meshes(n).forEach(m=>shadows.addShadowCaster(m));}
  n.position.set(o.lane*LANE+curve(o.d)-curve(distance),hill(o.d)-hill(distance)+(o.type==='coin'?(o.air?3.6:1.2)+Math.sin(visualTime*3+i)*.1:0),o.d-distance);if(o.type!=='coin'){n.rotation.y=(o.type==='ramp'||o.lane<0&&['sedan','taxi','delivery','suv'].includes(o.type)?Math.PI:0)+Math.atan(turn(o.d));n.rotation.x=-Math.atan(slope(o.d));}if(o.type==='coin')n.rotation.y=visualTime*2;
 }
 for(let i=0;i<oncoming.length;i++){const car=state.traffic[i],n=oncoming[i].n;n.position.set(car.lane*LANE+curve(car.d)-curve(distance),hill(car.d)-hill(distance),car.d-distance);n.rotation.y=Math.PI+Math.atan(turn(car.d));n.rotation.x=Math.atan(slope(car.d));}

 for(const [id,n]of visibleObjects)if(!wanted.has(id)){n.dispose();visibleObjects.delete(id);}
}
function resetWorld(){world.forEach(o=>o.n.dispose());world.length=0;visibleObjects.forEach(n=>n.dispose());visibleObjects.clear();lastSegment=Math.floor(state.distance/18)-3;lastBiome=-1;if(mode==='home')state.traffic.forEach((c,i)=>c.d=state.distance+45+i*42);}

function initAudio(){if(audio)return;audio=new (window.AudioContext||window.webkitAudioContext)();engineOsc=audio.createOscillator();engineGain=audio.createGain();engineOsc.type='triangle';engineOsc.frequency.value=65;engineGain.gain.value=0;engineOsc.connect(engineGain).connect(audio.destination);engineOsc.start();const buffer=audio.createBuffer(1,audio.sampleRate*2,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;const wind=audio.createBufferSource();wind.buffer=buffer;wind.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=950;windGain=audio.createGain();windGain.gain.value=0;wind.connect(filter).connect(windGain).connect(audio.destination);wind.start();}
// A short layered impact: low body thump, metal resonance and debris scrape.
function crashSound(){
 if(!soundOn||!audio)return;
 if(!crashBuffer){
  const duration=.85,rate=audio.sampleRate;
  crashBuffer=audio.createBuffer(1,Math.ceil(rate*duration),rate);
  const data=crashBuffer.getChannelData(0);let low=0;
  for(let i=0;i<data.length;i++){
   const t=i/rate,noise=Math.random()*2-1;low+=.16*(noise-low);
   const attack=Math.min(1,t/.002),end=Math.min(1,(duration-t)/.035);
   const thump=.48*Math.sin(2*Math.PI*(48*t+7*(1-Math.exp(-24*t))))*Math.exp(-14*t);
   const crunch=.5*(noise-low)*Math.exp(-23*t);
   const metal=(.16*Math.sin(2*Math.PI*683*t)+.11*Math.sin(2*Math.PI*1097*t)+.07*Math.sin(2*Math.PI*1783*t))*Math.exp(-9*t);
   const scrape=t>.035?.18*low*Math.exp(-4*(t-.035))*(.65+.35*Math.sin(2*Math.PI*39*t)):0;
   data[i]=Math.tanh((thump+crunch+metal+scrape)*1.5)*.8*attack*end;
  }
 }
 const source=audio.createBufferSource(),gain=audio.createGain();source.buffer=crashBuffer;gain.gain.value=.8;
 source.connect(gain).connect(audio.destination);source.onended=()=>{source.disconnect();gain.disconnect();};source.start();
}
function beep(freq,duration=.12){if(!soundOn||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.55,audio.currentTime+duration);g.gain.setValueAtTime(.065,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
$('sound').onclick=()=>{initAudio();audio.resume();soundOn=!soundOn;localStorage.setItem('rush-sound',soundOn?'on':'off');$('sound').textContent='音效 '+(soundOn?'開':'關');$('sound').setAttribute('aria-label',soundOn?'關閉音效':'開啟音效');};
async function start(){if(mode==='starting')return;initAudio();audio.resume();const previous=mode;mode='starting';$('start').disabled=true;$('retry').disabled=true;$('home-error').textContent='';try{run={id:Array.from(crypto.getRandomValues(new Uint32Array(4)),n=>n.toString(16).padStart(8,'0')).join(''),seed:crypto.getRandomValues(new Uint32Array(1))[0]};state=createState(run.seed);pending=[];acc=0;saved=false;Object.assign(motion,createMotion());resetWorld();mode='playing';show('home',false);show('overlay',false);show('result',false);show('pause-panel',false);show('hud');show('pause');show('touch-controls');show('speedlines');document.body.classList.add('playing');$('save-score').disabled=false;$('save-status').textContent='';$('nickname').value=localStorage.getItem('scooter-name')||'';if(audio)audio.resume();}catch(e){mode=previous;$('home-error').textContent=e.message;$('save-status').textContent=e.message;}finally{$('start').disabled=false;$('retry').disabled=false;}}
function pause(){if(mode!=='playing')return;mode='paused';pending=[];show('overlay');show('pause-panel');show('touch-controls',false);show('speedlines',false);}
function resume(){if(mode!=='paused')return;mode='playing';acc=0;lastTime=performance.now();show('overlay',false);show('pause-panel',false);show('touch-controls');show('speedlines');}
function home(){mode='home';state=createState(2026);run=null;resetWorld();show('overlay',false);show('pause-panel',false);show('result',false);show('home');show('hud',false);show('pause',false);show('touch-controls',false);show('speedlines',false);document.body.classList.remove('playing');}
function finish(){mode='ended';show('overlay');show('result');show('touch-controls',false);show('speedlines',false);show('pause',false);$('final-score').textContent=score(state).toLocaleString();$('final-detail').textContent=`騎行 ${Math.floor(state.distance).toLocaleString()} 公尺 · 收集 ${state.coins} 枚代幣`;}
function action(a){if(mode==='playing'&&pending.length<3)pending.push(a);}
$('start').onclick=start;$('retry').onclick=start;$('pause').onclick=pause;$('resume').onclick=resume;$('quit').onclick=home;$('result-home').onclick=home;
window.addEventListener('keydown',e=>{if(e.target instanceof HTMLInputElement)return;const map={ArrowLeft:'left',a:'left',A:'left',ArrowRight:'right',d:'right',D:'right',ArrowUp:'jump',' ':'jump',w:'jump',W:'jump'};if(map[e.key]){e.preventDefault();if(!e.repeat)action(map[e.key]);}if(e.key==='Escape'||e.key==='p'||e.key==='P'){if(mode==='playing')pause();else if(mode==='paused')resume();}});
let touch=null;canvas.addEventListener('pointerdown',e=>{touch={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointerup',e=>{if(!touch)return;const dx=e.clientX-touch.x,dy=e.clientY-touch.y;if(Math.max(Math.abs(dx),Math.abs(dy))>24){if(Math.abs(dx)>Math.abs(dy))action(dx>0?'right':'left');else if(dy<0)action('jump');}touch=null;});canvas.addEventListener('pointercancel',()=>touch=null);
document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('pointerdown',e=>{e.preventDefault();action(b.dataset.action);}));document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);
$('submit-score').onsubmit=async e=>{e.preventDefault();if(saved||!run)return;$('save-score').disabled=true;$('save-status').textContent='';try{const name=$('nickname').value.trim();const r=saveScore({id:run.id,name,score:score(state),distance:Math.floor(state.distance),coins:state.coins,created:Date.now()});saved=true;try{localStorage.setItem('scooter-name',name);}catch{}$('save-status').textContent=`已儲存，第 ${r.rank} 名！`;}catch(err){$('save-status').textContent=err.message;$('save-score').disabled=false;}};
let boardPeriod='all',boardRequest=0;
async function board(){const request=++boardRequest;show('overlay');show('board');$('scores').replaceChildren();const loading=document.createElement('li');loading.textContent='正在取得騎士榜…';$('scores').append(loading);try{const data={scores:leaderboard(boardPeriod)};if(request!==boardRequest)return;$('scores').replaceChildren();if(!data.scores.length){const li=document.createElement('li');li.textContent='第一位城市騎士，也許就是你。';$('scores').append(li);}data.scores.forEach((s,i)=>{const li=document.createElement('li');const rank=document.createElement('span'),name=document.createElement('span'),value=document.createElement('strong'),distance=document.createElement('small');rank.textContent=String(i+1).padStart(2,'0');name.textContent=s.name;value.textContent=s.score.toLocaleString();distance.textContent=s.distance.toLocaleString()+' m';value.append(distance);li.append(rank,name,value);$('scores').append(li);});}catch(e){loading.textContent=e.message;}}
$('show-board').onclick=board;$('close-board').onclick=()=>{boardRequest++;show('board',false);show('overlay',false);};document.querySelectorAll('[data-period]').forEach(b=>b.onclick=()=>{boardPeriod=b.dataset.period;document.querySelectorAll('[data-period]').forEach(x=>x.classList.toggle('active',x===b));board();});
function lighting(dt){const phase=(visualTime%120)/120;const daylight=(Math.cos((phase-.2)*Math.PI*2)+1)/2;const tunnel=biomeAt(state.distance)===2;const day=new Color3(.56,.74,.83),night=new Color3(.085,.12,.22),sunset=new Color3(.9,.66,.49);let sky=Color3.Lerp(night,day,daylight);if(daylight>.2&&daylight<.7)sky=Color3.Lerp(sky,sunset,Math.sin((daylight-.2)/.5*Math.PI)*.5);if(tunnel)sky=Color3.Lerp(sky,new Color3(.10,.17,.19),.65);scene.clearColor.set(sky.r,sky.g,sky.b,1);scene.fogColor=sky;hemi.intensity=tunnel?.23:.24+daylight*.24;sun.intensity=tunnel?.12:.12+daylight*2.5;scene.environmentIntensity=tunnel?.16:.18+daylight*.62;skybox.setEnabled(!tunnel);skybox.material.reflectionTexture.level=.12+daylight*.9;sun.diffuse=Color3.Lerp(new Color3(.55,.65,1),new Color3(1,.88,.72),daylight);headlight.intensity=tunnel?22:(1-daylight)*16;for(const {m,color}of glowMaterials)m.emissiveColor.copyFrom(color.scale(.05+(1-daylight)*.8));headlight.position.set(state.x,1.1+state.y,.9);headlight.direction.set(turn(state.distance+10)*.15,-.13,1).normalize();
const lightBase=Math.floor(state.distance/24)*24;for(let i=0;i<tunnelLights.length;i++){const d=lightBase+(i+1)*24,l=tunnelLights[i];l.position.set(ROAD_CENTER+curve(d)-curve(state.distance),6+hill(d)-hill(state.distance),d-state.distance);l.intensity=biomeAt(d)===2?100:0;}
sun.direction.set(-.7,-.65-daylight*.35,.4).normalize();hemi.groundColor.set(tunnel?.13:.24,tunnel?.16:.2,tunnel?.21:.16);
document.body.classList.toggle('night',daylight<.25&&mode!=='home');const label=daylight>.75?'晴朗午後':daylight>.35?(phase<.5?'黃昏時分':'晨光微熹'):'星光夜行';$('phase').textContent=(mode==='home'?'':BIOMES[biomeAt(state.distance)]+' · ')+label;}
function frame(now){const dt=Math.min(.08,(now-lastTime)/1000);lastTime=now;renderDt=dt;if(mode!=='paused'&&mode!=='ended'&&mode!=='crashed')visualTime+=dt;
 if(mode==='playing'){acc+=dt;while(acc>=STEP&&!state.dead){const actions=pending.splice(0);const previousHits=state.hits;step(state,actions);acc-=STEP;if(state.lastEvent==='coin'){beep(920,.08);$('coins').animate([{transform:'scale(1.5)',color:'#fff'},{transform:'scale(1)',color:'#bc8019'}],{duration:180});}if(state.lastEvent==='ramp'){beep(630,.35);}if(state.lastEvent==='jump')beep(420,.2);if(state.hits>previousHits){crashSound();document.body.classList.remove('impact');void document.body.offsetWidth;document.body.classList.add('impact');}if(state.lastEvent==='land'){beep(140,.06);landingImpulse(motion);}}if(state.dead){mode='crashed';crashAge=0;show('speedlines',false);show('touch-controls',false);}const b=biomeAt(state.distance);if(b!==lastBiome){lastBiome=b;}}
 if(mode==='crashed'){crashAge+=dt;if(crashAge>.7)finish();}
 if(rider){const homeView=mode==='home'||mode==='starting';advanceMotion(motion,{dt,laneDelta:state.lane*LANE-state.x,airborne:state.jumpAge>=0,speed:homeView?0:state.speed,active:mode==='playing'});updateWorld(state.distance);rider.position.set(homeView?0:state.x,homeView?0:state.y,0);rider.rotation.z=mode==='crashed'||mode==='ended'?Math.min(.6,crashAge*1.4):state.crashTicks>0?.25*Math.sin(state.crashTicks/42*Math.PI):homeView?0:motion.lean;rider.rotation.x=state.jumpAge>=0?-.30*Math.cos(state.jumpAge/state.jumpDuration*Math.PI):-Math.atan(slope(state.distance))+Math.sin(visualTime*32)*.007;rider.setEnabled(true);const mobile=innerWidth<700;const targetPos=homeView?(biomeAt(state.distance)===2?new Vector3(1,4.2,-10):mobile?new Vector3(4,3.6,-6):new Vector3(4,5,-8)):new Vector3(state.x*.3,3.5+state.y*.18,-7.8);camera.position=Vector3.Lerp(camera.position,targetPos,Math.min(1,dt*(homeView?4:9)));if(mobile&&!homeView)camera.position.x=state.x;camera.fov += ((homeView?.78:.96+Math.max(0,state.speed-40)*.006)-camera.fov)*Math.min(1,dt*3);camera.setTarget(homeView?(mobile?new Vector3(0,-1,0):new Vector3(-5,1.0,2)):new Vector3((mobile?state.x:state.x*.35)+curve(state.distance+16)-curve(state.distance),.9+hill(state.distance+16)-hill(state.distance),16));if(homeView)rider.rotation.y=Math.PI+.25;else rider.rotation.y=state.jumpAge>=0?0:Math.max(-.16,Math.min(.16,(state.lane*LANE-state.x)*.05));if(racer){racer.rotation.x=.12+(state.jumpAge>=0?.14*Math.sin(state.jumpAge/state.jumpDuration*Math.PI):0)-motion.compression*.8;racer.position.y=.4+motion.compression*.7;racer.rotation.z=-motion.lean*.18;if(spineJoint&&spineRest)spineJoint.rotationQuaternion=spineRest.multiply(Quaternion.RotationYawPitchRoll(-motion.lean*.12,-motion.compression*.8,-motion.lean*.1));}if(bike){bike.position.y=motion.compression*.35;for(const wheel of wheels){wheel.rotationQuaternion=null;wheel.rotation.x=motion.wheelAngle;}if(handlebar){handlebar.rotationQuaternion=null;handlebar.rotation.y=-motion.lean*.18;}}}
 lighting(dt);$('score').textContent=String(score(state)).padStart(5,'0');$('distance').textContent=Math.floor(state.distance).toLocaleString();$('coins').textContent=state.coins;$('hearts').textContent='♥ '.repeat(state.health)+'♡ '.repeat(3-state.health);$('speed').querySelector('b').textContent=state.dead?0:Math.round(state.speed*3.6);if(audio){windGain.gain.setTargetAtTime(soundOn&&mode==='playing'&&state.speed>0?.08+Math.max(0,state.speed-40)*.004:0,audio.currentTime,.2);engineGain.gain.setTargetAtTime(soundOn&&mode==='playing'?.055:0,audio.currentTime,.1);engineOsc.frequency.setTargetAtTime(60+state.speed*2,audio.currentTime,.1);}$('speedlines').style.setProperty('--wind',String(state.speed>0?Math.min(.85,.42+Math.max(0,state.speed-40)*.02):0));$('speedlines').style.setProperty('--duration',Math.max(.2,.9-state.speed*.01)+'s');scene.render();if(Math.floor(now/500)!==Math.floor((now-dt*1000)/500)){canvas.dataset.fps=String(Math.round(engine.getFps()));canvas.dataset.distance=String(Math.floor(state.distance));canvas.dataset.lane=String(state.lane);canvas.dataset.jump=state.y.toFixed(2);canvas.dataset.mode=mode;canvas.dataset.audio=audio?.state||'not-started';canvas.dataset.meshes=String(scene.meshes.length);}}
async function boot(){try{let count=0;await Promise.all(files.map(async name=>{const c=await SceneLoader.LoadAssetContainerAsync('./assets/models/',name+'.glb',scene);c.meshes.filter(m=>/collider|collision/i.test(m.name)).forEach(m=>m.dispose());for(const m of c.materials){if(!m.albedoColor)continue;m.maxSimultaneousLights=quality.name==='mobile'?4:6;const key=m.name.toLowerCase();if(/glass/.test(key)){m.metallic=.3;m.roughness=.2;}if(/lit-window|beacon/.test(key)||(name==='classic-street-lamp'&&/glass/.test(key))){glowMaterials.push({m,color:m.albedoColor.clone()});}for(const t of m.getActiveTextures())t.anisotropicFilteringLevel=quality.anisotropy;}assets.set(name,c);$('load-label').textContent=`準備出發 ${Math.round(++count/files.length*100)}%`;}));rider=new TransformNode('player',scene);bike=heightModel('road-sportbike',1.5);bike.parent=rider;bike.rotation.y=0;
const parts=bike.getDescendants(false);wheels=parts.filter(n=>/^wheel-(front|rear)-copy$/.test(n.name));handlebar=parts.find(n=>n.name==='handlebar-copy');const stand=parts.find(n=>n.name==='side-stand-copy');if(stand)stand.setEnabled(false);
for(const mesh of meshes(bike)){const m=mesh.material;if(!m)continue;m.environmentIntensity=1.1;const name=m.name.toLowerCase();if(name.includes('paint')){m.albedoColor=new Color3(.83,.07,.035);m.metallic=.35;m.roughness=.24;m.clearCoat.isEnabled=true;m.clearCoat.intensity=1;m.clearCoat.roughness=.16;}else if(name.includes('rubber')||name.includes('trim')){m.metallic=0;m.roughness=.86;}else if(name.includes('steel')||name.includes('alloy')){m.metallic=.92;m.roughness=.28;}else if(name.includes('glass')){m.metallic=.25;m.roughness=.13;}else if(name.includes('white')){m.emissiveColor=new Color3(.8,.74,.59);}}
racer=new TransformNode('rider assembly',scene);racer.parent=rider;racer.position.set(0,.4,.05);const body=new TransformNode('racing-rider',scene);const rig=assets.get('racing-rider').instantiateModelsToScene(n=>n+'-rider',false);rig.rootNodes.forEach(n=>n.parent=body);body.parent=racer;body.scaling.setAll(.9);body.position.set(0,-.15,-.18);spineJoint=body.getDescendants().find(n=>n.name==='spine_02-rider');headJoint=body.getDescendants().find(n=>n.name==='Head-rider');spineRest=spineJoint?.rotationQuaternion?.clone();helmet=heightModel('helmet',.43);helmet.parent=racer;helmet.position.set(0,1.21,-.005);helmet.rotation.y=0;for(const m of meshes(helmet).map(n=>n.material).filter(Boolean)){if(m.name.includes('paint')){m.albedoColor=new Color3(.94,.85,.65);m.metallic=.12;m.roughness=.25;m.clearCoat.isEnabled=true;}else if(m.name.includes('glass')){m.albedoColor=new Color3(.025,.055,.075);m.metallic=.6;m.roughness=.1;}}for(const m of meshes(body).map(n=>n.material).filter(Boolean)){m.metallic=0;m.roughness=.8;}meshes(rider).forEach(m=>shadows.addShadowCaster(m));for(let i=0;i<6;i++){const n=prefab(['sedan','taxi','delivery'][i%3],2.1);meshes(n).forEach(m=>shadows.addShadowCaster(m));oncoming.push({n});}$('load-label').textContent='出發，去兜風';$('start').disabled=false;engine.runRenderLoop(()=>frame(performance.now()));window.__game={get state(){return {...state,consumed:[...state.consumed]};},get mode(){return mode;},get ready(){return !!rider;},get stats(){return {fps:engine.getFps(),meshes:scene.meshes.length,shadowCasters:shadows.getShadowMap().renderList.length,biome:BIOMES[biomeAt(state.distance)]};}};}catch(e){console.error(e);$('load-label').textContent='素材載入失敗';$('home-error').textContent='請重新整理再試一次。'+e.message;}}
window.addEventListener('resize',updateResolution);boot();
